pip install pandas 
pip install numpy 
pip install scipy 
pip install matplotlib 
pip install seaborn 
pip install statsmodels 
pip install pandas_datareader 
pip install xgboost 
pip install lightgbm 
pip install scikit-learn 
pip install catboost 
pip install shap 
pip install plotly 
pip install cufflinks
pip install statsmodels
pip install shap
pip install chart_studio